# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6ddda1133d2a189b419263862ab1b4d0"
name = "Ocamba Hood"
handle = "ocamba-hood"
application_url = "https://another-happy-efficiency-walker.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bs-hq-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_files,read_products,read_script_tags,read_themes,write_content,write_files,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://another-happy-efficiency-walker.trycloudflare.com/auth/callback",
  "https://another-happy-efficiency-walker.trycloudflare.com/auth/shopify/callback",
  "https://another-happy-efficiency-walker.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
